export { default as Hero } from "./Hero";
export { default as Button } from "./Button";
export { default as Contact } from "./Contact";
export { default as Introduction } from "./Introduction";
export { default as Ourphilosophy } from "./Ourphilosophy";
export { default as Projects } from "./Projects";
export { default as Testimonials } from "./Testimonials";
export { default as WhyChooseUs } from "./WhyChooseUs";
export { default as AboutUs } from "./AboutUs";
